[package]
name = "good-bye-mshta"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_System_LibraryLoader", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
