[package]
name = "good-bye-mshta"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
winrt-notification = "0.5"
